@BASE_URL=http://localhost:3000/app/v1/customer
@AuthorizationToken=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImthbmhhaXlhQGdtYWlsLmNvbSIsInVzZXJfaWQiOiI2OTM1OTlhMmI3MzIzZWMwNWZkODA2NzkiLCJyb2xlIjoiYWRtaW4iLCJpYXQiOjE3NjUxMjA0MzEsImV4cCI6MTc2NTEyMTMzMX0.YEufZ2HLDJJ0qG1OXho0pR9NSfF7uA9ivwNCpXOaS9Q
GET {{BASE_URL}}/
Authorization: Bearer {{AuthorizationToken}}

###

GET {{BASE_URL}}/6935800c2926661a795338ae
Authorization: Bearer {{AuthorizationToken}}

###

PUT {{BASE_URL}}/update/6935998bb7323ec05fd80676
Authorization: Bearer {{AuthorizationToken}}
Content-Type: application/json

{
    "password":"123"
}

###

DELETE {{BASE_URL}}/delete-all
Authorization: Bearer {{AuthorizationToken}}