@BASE_URL=http://localhost:3000/app/v1/customer

POST {{BASE_URL}}/sign-up
Content-Type: application/json

{
    "email":"kanhaiya@gmail.com",
    "password":"123",
    "role":"admin"
}

###

GET {{BASE_URL}}/sign-in
Content-Type: application/json

{
    "email":"kanhaiya@gmail.com",
    "password":"123"
}

