@BASE_URL=http://localhost:3000/app/v1/customer

POST {{BASE_URL}}/sign-up
Content-Type: application/json

{
    "email":"kanhaiya@123",
    "password":"123@12"
}

###

GET {{BASE_URL}}/sign-in
Content-Type: application/json

{
    "email":"kanhaiya@123",
    "password":"123@12"
}


###

GET {{BASE_URL}}/testing
