@BASE_URL=http://localhost:3000/app/v1

GET {{BASE_URL}}
# Content-Type: application/json

###
GET {{BASE_URL}}/todos


###
GET {{BASE_URL}}/todo/692a8ba690f818df475d995d

###

POST {{BASE_URL}}/add-todo
Content-Type: application/json

{
    "title":"do home work",
    "priority":"Low",
    "due":"",
    "status":"completed"
}


###

DELETE {{BASE_URL}}/delete/692a8ba690f818df475d995d